language: python
python:
  - "3.5"
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
script:
  - make test 
  - nosetests --with-coverage
  - coverage run test_rpn.py test
after_success:
  - coveralls
